//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATSData.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportInventoryBalanceRequest", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Inventory")]
    [System.SerializableAttribute()]
    public partial class ReportInventoryBalanceRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ATSData.ServiceReference1.ReportInventoryBalanceRequest.ItemBalance[] ItemBalancesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageRequestedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MessageSequenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReliefBatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReportingDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SyncUpMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SyncUpRequestDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCN {
            get {
                return this.CCNField;
            }
            set {
                if ((object.ReferenceEquals(this.CCNField, value) != true)) {
                    this.CCNField = value;
                    this.RaisePropertyChanged("CCN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ATSData.ServiceReference1.ReportInventoryBalanceRequest.ItemBalance[] ItemBalances {
            get {
                return this.ItemBalancesField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemBalancesField, value) != true)) {
                    this.ItemBalancesField = value;
                    this.RaisePropertyChanged("ItemBalances");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageRequested {
            get {
                return this.MessageRequestedField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageRequestedField, value) != true)) {
                    this.MessageRequestedField = value;
                    this.RaisePropertyChanged("MessageRequested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageSequenceNumber {
            get {
                return this.MessageSequenceNumberField;
            }
            set {
                if ((this.MessageSequenceNumberField.Equals(value) != true)) {
                    this.MessageSequenceNumberField = value;
                    this.RaisePropertyChanged("MessageSequenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReliefBatchId {
            get {
                return this.ReliefBatchIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReliefBatchIdField, value) != true)) {
                    this.ReliefBatchIdField = value;
                    this.RaisePropertyChanged("ReliefBatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReportingDateTime {
            get {
                return this.ReportingDateTimeField;
            }
            set {
                if ((this.ReportingDateTimeField.Equals(value) != true)) {
                    this.ReportingDateTimeField = value;
                    this.RaisePropertyChanged("ReportingDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SyncUpMessage {
            get {
                return this.SyncUpMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.SyncUpMessageField, value) != true)) {
                    this.SyncUpMessageField = value;
                    this.RaisePropertyChanged("SyncUpMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SyncUpRequestDateTime {
            get {
                return this.SyncUpRequestDateTimeField;
            }
            set {
                if ((this.SyncUpRequestDateTimeField.Equals(value) != true)) {
                    this.SyncUpRequestDateTimeField = value;
                    this.RaisePropertyChanged("SyncUpRequestDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ReportInventoryBalanceRequest.ItemBalance", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Inventory")]
        [System.SerializableAttribute()]
        public partial class ItemBalance : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private ATSData.ServiceReference1.ReportInventoryBalanceRequest.ItemBalance.LocationBalance[] AllLocationBalanceField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string FGAField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string FGAProxyMODField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string FGAProxySKUField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public ATSData.ServiceReference1.ReportInventoryBalanceRequest.ItemBalance.LocationBalance[] AllLocationBalance {
                get {
                    return this.AllLocationBalanceField;
                }
                set {
                    if ((object.ReferenceEquals(this.AllLocationBalanceField, value) != true)) {
                        this.AllLocationBalanceField = value;
                        this.RaisePropertyChanged("AllLocationBalance");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string FGA {
                get {
                    return this.FGAField;
                }
                set {
                    if ((object.ReferenceEquals(this.FGAField, value) != true)) {
                        this.FGAField = value;
                        this.RaisePropertyChanged("FGA");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string FGAProxyMOD {
                get {
                    return this.FGAProxyMODField;
                }
                set {
                    if ((object.ReferenceEquals(this.FGAProxyMODField, value) != true)) {
                        this.FGAProxyMODField = value;
                        this.RaisePropertyChanged("FGAProxyMOD");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string FGAProxySKU {
                get {
                    return this.FGAProxySKUField;
                }
                set {
                    if ((object.ReferenceEquals(this.FGAProxySKUField, value) != true)) {
                        this.FGAProxySKUField = value;
                        this.RaisePropertyChanged("FGAProxySKU");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
            
            [System.Diagnostics.DebuggerStepThroughAttribute()]
            [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
            [System.Runtime.Serialization.DataContractAttribute(Name="ReportInventoryBalanceRequest.ItemBalance.LocationBalance", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Inventory")]
            [System.SerializableAttribute()]
            public partial class LocationBalance : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
                
                [System.NonSerializedAttribute()]
                private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string LocationCodeField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private int OnHandQuantityField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private ATSData.ServiceReference1.ReportInventoryBalanceRequest.ItemBalance.ReliefOrder[] ReliefOrdersField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private int ShippedQuantityField;
                
                public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                    get {
                        return this.extensionDataField;
                    }
                    set {
                        this.extensionDataField = value;
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute()]
                public string LocationCode {
                    get {
                        return this.LocationCodeField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.LocationCodeField, value) != true)) {
                            this.LocationCodeField = value;
                            this.RaisePropertyChanged("LocationCode");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute()]
                public int OnHandQuantity {
                    get {
                        return this.OnHandQuantityField;
                    }
                    set {
                        if ((this.OnHandQuantityField.Equals(value) != true)) {
                            this.OnHandQuantityField = value;
                            this.RaisePropertyChanged("OnHandQuantity");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute()]
                public ATSData.ServiceReference1.ReportInventoryBalanceRequest.ItemBalance.ReliefOrder[] ReliefOrders {
                    get {
                        return this.ReliefOrdersField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.ReliefOrdersField, value) != true)) {
                            this.ReliefOrdersField = value;
                            this.RaisePropertyChanged("ReliefOrders");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute()]
                public int ShippedQuantity {
                    get {
                        return this.ShippedQuantityField;
                    }
                    set {
                        if ((this.ShippedQuantityField.Equals(value) != true)) {
                            this.ShippedQuantityField = value;
                            this.RaisePropertyChanged("ShippedQuantity");
                        }
                    }
                }
                
                public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
                
                protected void RaisePropertyChanged(string propertyName) {
                    System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                    if ((propertyChanged != null)) {
                        propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                    }
                }
            }
            
            [System.Diagnostics.DebuggerStepThroughAttribute()]
            [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
            [System.Runtime.Serialization.DataContractAttribute(Name="ReportInventoryBalanceRequest.ItemBalance.ReliefOrder", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Inventory")]
            [System.SerializableAttribute()]
            public partial class ReliefOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
                
                [System.NonSerializedAttribute()]
                private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string OrderNumberField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private int QuantityField;
                
                public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                    get {
                        return this.extensionDataField;
                    }
                    set {
                        this.extensionDataField = value;
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute()]
                public string OrderNumber {
                    get {
                        return this.OrderNumberField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.OrderNumberField, value) != true)) {
                            this.OrderNumberField = value;
                            this.RaisePropertyChanged("OrderNumber");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute()]
                public int Quantity {
                    get {
                        return this.QuantityField;
                    }
                    set {
                        if ((this.QuantityField.Equals(value) != true)) {
                            this.QuantityField = value;
                            this.RaisePropertyChanged("Quantity");
                        }
                    }
                }
                
                public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
                
                protected void RaisePropertyChanged(string propertyName) {
                    System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                    if ((propertyChanged != null)) {
                        propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                    }
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportInventoryBalanceResponse", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Inventory")]
    [System.SerializableAttribute()]
    public partial class ReportInventoryBalanceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
        "ct")]
    [System.SerializableAttribute()]
    public partial class ATSFaultDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepublishMessageRequest", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Inventory")]
    [System.SerializableAttribute()]
    public partial class RepublishMessageRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SequenceNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCN {
            get {
                return this.CCNField;
            }
            set {
                if ((object.ReferenceEquals(this.CCNField, value) != true)) {
                    this.CCNField = value;
                    this.RaisePropertyChanged("CCN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SequenceNumber {
            get {
                return this.SequenceNumberField;
            }
            set {
                if ((this.SequenceNumberField.Equals(value) != true)) {
                    this.SequenceNumberField = value;
                    this.RaisePropertyChanged("SequenceNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepublishMessageResponse", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Inventory")]
    [System.SerializableAttribute()]
    public partial class RepublishMessageResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageResponse {
            get {
                return this.MessageResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageResponseField, value) != true)) {
                    this.MessageResponseField = value;
                    this.RaisePropertyChanged("MessageResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMaxMessageSequenceNumberRequest", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Inventory")]
    [System.SerializableAttribute()]
    public partial class GetMaxMessageSequenceNumberRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCNField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCN {
            get {
                return this.CCNField;
            }
            set {
                if ((object.ReferenceEquals(this.CCNField, value) != true)) {
                    this.CCNField = value;
                    this.RaisePropertyChanged("CCN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMaxMessageSequenceNumberResponse", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Inventory")]
    [System.SerializableAttribute()]
    public partial class GetMaxMessageSequenceNumberResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCallSuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxMessageSequenceNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCallSuccessful {
            get {
                return this.IsCallSuccessfulField;
            }
            set {
                if ((this.IsCallSuccessfulField.Equals(value) != true)) {
                    this.IsCallSuccessfulField = value;
                    this.RaisePropertyChanged("IsCallSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxMessageSequenceNumber {
            get {
                return this.MaxMessageSequenceNumberField;
            }
            set {
                if ((this.MaxMessageSequenceNumberField.Equals(value) != true)) {
                    this.MaxMessageSequenceNumberField = value;
                    this.RaisePropertyChanged("MaxMessageSequenceNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailableToSellBySKURequest", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Inventory")]
    [System.SerializableAttribute()]
    public partial class AvailableToSellBySKURequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailableToSellBySKUResponse", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Inventory")]
    [System.SerializableAttribute()]
    public partial class AvailableToSellBySKUResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ATSData.ServiceReference1.ProductATS ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ATSData.ServiceReference1.ProductATS Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((this.SuccessfulField.Equals(value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductATS", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services")]
    [System.SerializableAttribute()]
    public partial class ProductATS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvailableToSellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InventoryLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InventoryStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFastTrackEligibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LeadTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvailableToSell {
            get {
                return this.AvailableToSellField;
            }
            set {
                if ((this.AvailableToSellField.Equals(value) != true)) {
                    this.AvailableToSellField = value;
                    this.RaisePropertyChanged("AvailableToSell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InventoryLevel {
            get {
                return this.InventoryLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.InventoryLevelField, value) != true)) {
                    this.InventoryLevelField = value;
                    this.RaisePropertyChanged("InventoryLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InventoryStatus {
            get {
                return this.InventoryStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.InventoryStatusField, value) != true)) {
                    this.InventoryStatusField = value;
                    this.RaisePropertyChanged("InventoryStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFastTrackEligible {
            get {
                return this.IsFastTrackEligibleField;
            }
            set {
                if ((this.IsFastTrackEligibleField.Equals(value) != true)) {
                    this.IsFastTrackEligibleField = value;
                    this.RaisePropertyChanged("IsFastTrackEligible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeadTime {
            get {
                return this.LeadTimeField;
            }
            set {
                if ((this.LeadTimeField.Equals(value) != true)) {
                    this.LeadTimeField = value;
                    this.RaisePropertyChanged("LeadTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRegionalInventoryRequest", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Inventory")]
    [System.SerializableAttribute()]
    public partial class GetRegionalInventoryRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRegionalInventoryResponse", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Inventory")]
    [System.SerializableAttribute()]
    public partial class GetRegionalInventoryResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InventoryItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InventoryItems {
            get {
                return this.InventoryItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.InventoryItemsField, value) != true)) {
                    this.InventoryItemsField = value;
                    this.RaisePropertyChanged("InventoryItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((this.SuccessfulField.Equals(value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.dell.com/AvailableToSell/Inventory", ConfigurationName="ServiceReference1.InventoryService")]
    public interface InventoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Inventory/InventoryService/ReportInventor" +
            "yBalance", ReplyAction="http://schemas.dell.com/AvailableToSell/Inventory/InventoryService/ReportInventor" +
            "yBalanceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ServiceReference1.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Inventory/InventoryService/ReportInventor" +
            "yBalanceATSFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        ATSData.ServiceReference1.ReportInventoryBalanceResponse ReportInventoryBalance(ATSData.ServiceReference1.ReportInventoryBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Inventory/InventoryService/RepublishMessa" +
            "ge", ReplyAction="http://schemas.dell.com/AvailableToSell/Inventory/InventoryService/RepublishMessa" +
            "geResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ServiceReference1.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Inventory/InventoryService/RepublishMessa" +
            "geATSFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        ATSData.ServiceReference1.RepublishMessageResponse RepublishMessage(ATSData.ServiceReference1.RepublishMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Inventory/InventoryService/GetMaxMessageS" +
            "equenceNumber", ReplyAction="http://schemas.dell.com/AvailableToSell/Inventory/InventoryService/GetMaxMessageS" +
            "equenceNumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ServiceReference1.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Inventory/InventoryService/GetMaxMessageS" +
            "equenceNumberATSFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        ATSData.ServiceReference1.GetMaxMessageSequenceNumberResponse GetMaxMessageSequenceNumber(ATSData.ServiceReference1.GetMaxMessageSequenceNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Inventory/InventoryService/AvailableToSel" +
            "lBySKU", ReplyAction="http://schemas.dell.com/AvailableToSell/Inventory/InventoryService/AvailableToSel" +
            "lBySKUResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ServiceReference1.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Inventory/InventoryService/AvailableToSel" +
            "lBySKUATSFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        ATSData.ServiceReference1.AvailableToSellBySKUResponse AvailableToSellBySKU(ATSData.ServiceReference1.AvailableToSellBySKURequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Inventory/InventoryService/GetRegionalInv" +
            "entory", ReplyAction="http://schemas.dell.com/AvailableToSell/Inventory/InventoryService/GetRegionalInv" +
            "entoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ServiceReference1.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Inventory/InventoryService/GetRegionalInv" +
            "entoryATSFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        ATSData.ServiceReference1.GetRegionalInventoryResponse GetRegionalInventory(ATSData.ServiceReference1.GetRegionalInventoryRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InventoryServiceChannel : ATSData.ServiceReference1.InventoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InventoryServiceClient : System.ServiceModel.ClientBase<ATSData.ServiceReference1.InventoryService>, ATSData.ServiceReference1.InventoryService {
        
        public InventoryServiceClient() {
        }
        
        public InventoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InventoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ATSData.ServiceReference1.ReportInventoryBalanceResponse ReportInventoryBalance(ATSData.ServiceReference1.ReportInventoryBalanceRequest request) {
            return base.Channel.ReportInventoryBalance(request);
        }
        
        public ATSData.ServiceReference1.RepublishMessageResponse RepublishMessage(ATSData.ServiceReference1.RepublishMessageRequest request) {
            return base.Channel.RepublishMessage(request);
        }
        
        public ATSData.ServiceReference1.GetMaxMessageSequenceNumberResponse GetMaxMessageSequenceNumber(ATSData.ServiceReference1.GetMaxMessageSequenceNumberRequest request) {
            return base.Channel.GetMaxMessageSequenceNumber(request);
        }
        
        public ATSData.ServiceReference1.AvailableToSellBySKUResponse AvailableToSellBySKU(ATSData.ServiceReference1.AvailableToSellBySKURequest request) {
            return base.Channel.AvailableToSellBySKU(request);
        }
        
        public ATSData.ServiceReference1.GetRegionalInventoryResponse GetRegionalInventory(ATSData.ServiceReference1.GetRegionalInventoryRequest request) {
            return base.Channel.GetRegionalInventory(request);
        }
    }
}
