//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATSData.ATSUtilityService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchProduct", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Utilities")]
    [System.SerializableAttribute()]
    public partial class SearchProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductEventLogInfo", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Utilities")]
    [System.SerializableAttribute()]
    public partial class ProductEventLogInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ActionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CancelledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CommittedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ExpiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OnhandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PostCheckOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PreCheckOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ActionDate {
            get {
                return this.ActionDateField;
            }
            set {
                if ((this.ActionDateField.Equals(value) != true)) {
                    this.ActionDateField = value;
                    this.RaisePropertyChanged("ActionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Available {
            get {
                return this.AvailableField;
            }
            set {
                if ((this.AvailableField.Equals(value) != true)) {
                    this.AvailableField = value;
                    this.RaisePropertyChanged("Available");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Cancelled {
            get {
                return this.CancelledField;
            }
            set {
                if ((this.CancelledField.Equals(value) != true)) {
                    this.CancelledField = value;
                    this.RaisePropertyChanged("Cancelled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Committed {
            get {
                return this.CommittedField;
            }
            set {
                if ((this.CommittedField.Equals(value) != true)) {
                    this.CommittedField = value;
                    this.RaisePropertyChanged("Committed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Event {
            get {
                return this.EventField;
            }
            set {
                if ((object.ReferenceEquals(this.EventField, value) != true)) {
                    this.EventField = value;
                    this.RaisePropertyChanged("Event");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Expired {
            get {
                return this.ExpiredField;
            }
            set {
                if ((this.ExpiredField.Equals(value) != true)) {
                    this.ExpiredField = value;
                    this.RaisePropertyChanged("Expired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Onhand {
            get {
                return this.OnhandField;
            }
            set {
                if ((this.OnhandField.Equals(value) != true)) {
                    this.OnhandField = value;
                    this.RaisePropertyChanged("Onhand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PostCheckOut {
            get {
                return this.PostCheckOutField;
            }
            set {
                if ((this.PostCheckOutField.Equals(value) != true)) {
                    this.PostCheckOutField = value;
                    this.RaisePropertyChanged("PostCheckOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PreCheckOut {
            get {
                return this.PreCheckOutField;
            }
            set {
                if ((this.PreCheckOutField.Equals(value) != true)) {
                    this.PreCheckOutField = value;
                    this.RaisePropertyChanged("PreCheckOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
        "ct")]
    [System.SerializableAttribute()]
    public partial class ATSFaultDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDetails", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Utilities")]
    [System.SerializableAttribute()]
    public partial class ProductDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FGAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FGA {
            get {
                return this.FGAField;
            }
            set {
                if ((object.ReferenceEquals(this.FGAField, value) != true)) {
                    this.FGAField = value;
                    this.RaisePropertyChanged("FGA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegionInfo", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Utilities")]
    [System.SerializableAttribute()]
    public partial class RegionInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacilityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FacilityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacilityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RegionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId {
            get {
                return this.CountryIdField;
            }
            set {
                if ((this.CountryIdField.Equals(value) != true)) {
                    this.CountryIdField = value;
                    this.RaisePropertyChanged("CountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacilityCode {
            get {
                return this.FacilityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FacilityCodeField, value) != true)) {
                    this.FacilityCodeField = value;
                    this.RaisePropertyChanged("FacilityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FacilityId {
            get {
                return this.FacilityIdField;
            }
            set {
                if ((this.FacilityIdField.Equals(value) != true)) {
                    this.FacilityIdField = value;
                    this.RaisePropertyChanged("FacilityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacilityName {
            get {
                return this.FacilityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FacilityNameField, value) != true)) {
                    this.FacilityNameField = value;
                    this.RaisePropertyChanged("FacilityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RegionId {
            get {
                return this.RegionIdField;
            }
            set {
                if ((this.RegionIdField.Equals(value) != true)) {
                    this.RegionIdField = value;
                    this.RaisePropertyChanged("RegionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionName {
            get {
                return this.RegionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionNameField, value) != true)) {
                    this.RegionNameField = value;
                    this.RaisePropertyChanged("RegionName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreCheckOutReportRequest", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Utilities")]
    [System.SerializableAttribute()]
    public partial class PreCheckOutReportRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RegionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegionId {
            get {
                return this.RegionIdField;
            }
            set {
                if ((this.RegionIdField.Equals(value) != true)) {
                    this.RegionIdField = value;
                    this.RaisePropertyChanged("RegionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreCheckOutReportRatio", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Utilities")]
    [System.SerializableAttribute()]
    public partial class PreCheckOutReportRatio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostCheckOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PreCheckOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float RatioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SummaryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandName {
            get {
                return this.BrandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandNameField, value) != true)) {
                    this.BrandNameField = value;
                    this.RaisePropertyChanged("BrandName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostCheckOut {
            get {
                return this.PostCheckOutField;
            }
            set {
                if ((this.PostCheckOutField.Equals(value) != true)) {
                    this.PostCheckOutField = value;
                    this.RaisePropertyChanged("PostCheckOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PreCheckOut {
            get {
                return this.PreCheckOutField;
            }
            set {
                if ((this.PreCheckOutField.Equals(value) != true)) {
                    this.PreCheckOutField = value;
                    this.RaisePropertyChanged("PreCheckOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Ratio {
            get {
                return this.RatioField;
            }
            set {
                if ((this.RatioField.Equals(value) != true)) {
                    this.RatioField = value;
                    this.RaisePropertyChanged("Ratio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SummaryDate {
            get {
                return this.SummaryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryDateField, value) != true)) {
                    this.SummaryDateField = value;
                    this.RaisePropertyChanged("SummaryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductInventory", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Utilities")]
    [System.SerializableAttribute()]
    public partial class ProductInventory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SelectedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Selected {
            get {
                return this.SelectedField;
            }
            set {
                if ((this.SelectedField.Equals(value) != true)) {
                    this.SelectedField = value;
                    this.RaisePropertyChanged("Selected");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSalesHistory", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Utilities")]
    [System.SerializableAttribute()]
    public partial class ProductSalesHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AvailableQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FGAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FridayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MondayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OnHandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Prev8WeeksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SaturdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SundayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ThursdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TuesdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WednesdayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AvailableQuantity {
            get {
                return this.AvailableQuantityField;
            }
            set {
                if ((this.AvailableQuantityField.Equals(value) != true)) {
                    this.AvailableQuantityField = value;
                    this.RaisePropertyChanged("AvailableQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FGA {
            get {
                return this.FGAField;
            }
            set {
                if ((object.ReferenceEquals(this.FGAField, value) != true)) {
                    this.FGAField = value;
                    this.RaisePropertyChanged("FGA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Friday {
            get {
                return this.FridayField;
            }
            set {
                if ((this.FridayField.Equals(value) != true)) {
                    this.FridayField = value;
                    this.RaisePropertyChanged("Friday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Monday {
            get {
                return this.MondayField;
            }
            set {
                if ((this.MondayField.Equals(value) != true)) {
                    this.MondayField = value;
                    this.RaisePropertyChanged("Monday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OnHand {
            get {
                return this.OnHandField;
            }
            set {
                if ((this.OnHandField.Equals(value) != true)) {
                    this.OnHandField = value;
                    this.RaisePropertyChanged("OnHand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Prev8Weeks {
            get {
                return this.Prev8WeeksField;
            }
            set {
                if ((this.Prev8WeeksField.Equals(value) != true)) {
                    this.Prev8WeeksField = value;
                    this.RaisePropertyChanged("Prev8Weeks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Saturday {
            get {
                return this.SaturdayField;
            }
            set {
                if ((this.SaturdayField.Equals(value) != true)) {
                    this.SaturdayField = value;
                    this.RaisePropertyChanged("Saturday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sunday {
            get {
                return this.SundayField;
            }
            set {
                if ((this.SundayField.Equals(value) != true)) {
                    this.SundayField = value;
                    this.RaisePropertyChanged("Sunday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Thursday {
            get {
                return this.ThursdayField;
            }
            set {
                if ((this.ThursdayField.Equals(value) != true)) {
                    this.ThursdayField = value;
                    this.RaisePropertyChanged("Thursday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tuesday {
            get {
                return this.TuesdayField;
            }
            set {
                if ((this.TuesdayField.Equals(value) != true)) {
                    this.TuesdayField = value;
                    this.RaisePropertyChanged("Tuesday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Wednesday {
            get {
                return this.WednesdayField;
            }
            set {
                if ((this.WednesdayField.Equals(value) != true)) {
                    this.WednesdayField = value;
                    this.RaisePropertyChanged("Wednesday");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InTransitHistoryResults", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Utilities")]
    [System.SerializableAttribute()]
    public partial class InTransitHistoryResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EstimatedArrivalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InventroyOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MergeCenterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuanityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShippingFromFacilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransportModeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Assin {
            get {
                return this.AssinField;
            }
            set {
                if ((object.ReferenceEquals(this.AssinField, value) != true)) {
                    this.AssinField = value;
                    this.RaisePropertyChanged("Assin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EstimatedArrival {
            get {
                return this.EstimatedArrivalField;
            }
            set {
                if ((this.EstimatedArrivalField.Equals(value) != true)) {
                    this.EstimatedArrivalField = value;
                    this.RaisePropertyChanged("EstimatedArrival");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InventroyOwner {
            get {
                return this.InventroyOwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.InventroyOwnerField, value) != true)) {
                    this.InventroyOwnerField = value;
                    this.RaisePropertyChanged("InventroyOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MergeCenter {
            get {
                return this.MergeCenterField;
            }
            set {
                if ((object.ReferenceEquals(this.MergeCenterField, value) != true)) {
                    this.MergeCenterField = value;
                    this.RaisePropertyChanged("MergeCenter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Part {
            get {
                return this.PartField;
            }
            set {
                if ((object.ReferenceEquals(this.PartField, value) != true)) {
                    this.PartField = value;
                    this.RaisePropertyChanged("Part");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quanity {
            get {
                return this.QuanityField;
            }
            set {
                if ((this.QuanityField.Equals(value) != true)) {
                    this.QuanityField = value;
                    this.RaisePropertyChanged("Quanity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingFromFacility {
            get {
                return this.ShippingFromFacilityField;
            }
            set {
                if ((object.ReferenceEquals(this.ShippingFromFacilityField, value) != true)) {
                    this.ShippingFromFacilityField = value;
                    this.RaisePropertyChanged("ShippingFromFacility");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransportMode {
            get {
                return this.TransportModeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransportModeField, value) != true)) {
                    this.TransportModeField = value;
                    this.RaisePropertyChanged("TransportMode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesChannelOptions", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Utilities")]
    public enum SalesChannelOptions : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Offline = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Online = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionMode", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Utilities")]
    public enum ActionMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Add = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntransitRequest", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Utilities")]
    [System.SerializableAttribute()]
    public partial class IntransitRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EstimatedArrivalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FulfillmentLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManagedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MergedCenterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransportModeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EstimatedArrival {
            get {
                return this.EstimatedArrivalField;
            }
            set {
                if ((this.EstimatedArrivalField.Equals(value) != true)) {
                    this.EstimatedArrivalField = value;
                    this.RaisePropertyChanged("EstimatedArrival");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FulfillmentLocation {
            get {
                return this.FulfillmentLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.FulfillmentLocationField, value) != true)) {
                    this.FulfillmentLocationField = value;
                    this.RaisePropertyChanged("FulfillmentLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagedBy {
            get {
                return this.ManagedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagedByField, value) != true)) {
                    this.ManagedByField = value;
                    this.RaisePropertyChanged("ManagedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MergedCenter {
            get {
                return this.MergedCenterField;
            }
            set {
                if ((object.ReferenceEquals(this.MergedCenterField, value) != true)) {
                    this.MergedCenterField = value;
                    this.RaisePropertyChanged("MergedCenter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipmentId {
            get {
                return this.ShipmentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipmentIdField, value) != true)) {
                    this.ShipmentIdField = value;
                    this.RaisePropertyChanged("ShipmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransportMode {
            get {
                return this.TransportModeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransportModeField, value) != true)) {
                    this.TransportModeField = value;
                    this.RaisePropertyChanged("TransportMode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntransitResponse", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Utilities")]
    [System.SerializableAttribute()]
    public partial class IntransitResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((this.SuccessfulField.Equals(value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GOPTestHarnessOnHandRequest", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Utilities")]
    [System.SerializableAttribute()]
    public partial class GOPTestHarnessOnHandRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OnhandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationCode {
            get {
                return this.LocationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationCodeField, value) != true)) {
                    this.LocationCodeField = value;
                    this.RaisePropertyChanged("LocationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Onhand {
            get {
                return this.OnhandField;
            }
            set {
                if ((this.OnhandField.Equals(value) != true)) {
                    this.OnhandField = value;
                    this.RaisePropertyChanged("Onhand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GOPTestHarnessOnHandResponse", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Utilities")]
    [System.SerializableAttribute()]
    public partial class GOPTestHarnessOnHandResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((this.SuccessfulField.Equals(value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReliefOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Utilities")]
    [System.SerializableAttribute()]
    public partial class ReliefOrderRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FGAIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FgaProxyModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FGAId {
            get {
                return this.FGAIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FGAIdField, value) != true)) {
                    this.FGAIdField = value;
                    this.RaisePropertyChanged("FGAId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FgaProxyMod {
            get {
                return this.FgaProxyModField;
            }
            set {
                if ((object.ReferenceEquals(this.FgaProxyModField, value) != true)) {
                    this.FgaProxyModField = value;
                    this.RaisePropertyChanged("FgaProxyMod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((this.OrderNumberField.Equals(value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReliefOrderResponse", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Utilities")]
    [System.SerializableAttribute()]
    public partial class ReliefOrderResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((this.SuccessfulField.Equals(value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionDetailResponse", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Utilities")]
    [System.SerializableAttribute()]
    public partial class TransactionDetailResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastUpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReservationStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedAt {
            get {
                return this.LastUpdatedAtField;
            }
            set {
                if ((this.LastUpdatedAtField.Equals(value) != true)) {
                    this.LastUpdatedAtField = value;
                    this.RaisePropertyChanged("LastUpdatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdatedBy {
            get {
                return this.LastUpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.LastUpdatedByField, value) != true)) {
                    this.LastUpdatedByField = value;
                    this.RaisePropertyChanged("LastUpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationStatus {
            get {
                return this.ReservationStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationStatusField, value) != true)) {
                    this.ReservationStatusField = value;
                    this.RaisePropertyChanged("ReservationStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DbJobDetailsResponse", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.Utilities")]
    [System.SerializableAttribute()]
    public partial class DbJobDetailsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExecutionStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastRunTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManualOverrideField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NextRunTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScheduleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Action {
            get {
                return this.ActionField;
            }
            set {
                if ((this.ActionField.Equals(value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExecutionStatus {
            get {
                return this.ExecutionStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ExecutionStatusField, value) != true)) {
                    this.ExecutionStatusField = value;
                    this.RaisePropertyChanged("ExecutionStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobName {
            get {
                return this.JobNameField;
            }
            set {
                if ((object.ReferenceEquals(this.JobNameField, value) != true)) {
                    this.JobNameField = value;
                    this.RaisePropertyChanged("JobName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastRunTime {
            get {
                return this.LastRunTimeField;
            }
            set {
                if ((this.LastRunTimeField.Equals(value) != true)) {
                    this.LastRunTimeField = value;
                    this.RaisePropertyChanged("LastRunTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManualOverride {
            get {
                return this.ManualOverrideField;
            }
            set {
                if ((object.ReferenceEquals(this.ManualOverrideField, value) != true)) {
                    this.ManualOverrideField = value;
                    this.RaisePropertyChanged("ManualOverride");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NextRunTime {
            get {
                return this.NextRunTimeField;
            }
            set {
                if ((this.NextRunTimeField.Equals(value) != true)) {
                    this.NextRunTimeField = value;
                    this.RaisePropertyChanged("NextRunTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Schedule {
            get {
                return this.ScheduleField;
            }
            set {
                if ((object.ReferenceEquals(this.ScheduleField, value) != true)) {
                    this.ScheduleField = value;
                    this.RaisePropertyChanged("Schedule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.dell.com/AvailableToSell/Utilities", ConfigurationName="ATSUtilityService.ATSUtilityService")]
    public interface ATSUtilityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetProductEve" +
            "ntLogInformation", ReplyAction="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetProductEve" +
            "ntLogInformationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ATSUtilityService.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetProductEve" +
            "ntLogInformationATSFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        ATSData.ATSUtilityService.ProductEventLogInfo[] GetProductEventLogInformation(ATSData.ATSUtilityService.SearchProduct request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetProductDet" +
            "ails", ReplyAction="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetProductDet" +
            "ailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ATSUtilityService.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetProductDet" +
            "ailsATSFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        ATSData.ATSUtilityService.ProductDetails GetProductDetails(ATSData.ATSUtilityService.SearchProduct request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetRegionList" +
            "", ReplyAction="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetRegionList" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ATSUtilityService.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetRegionList" +
            "ATSFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        ATSData.ATSUtilityService.RegionInfo[] GetRegionList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetCountryLis" +
            "t", ReplyAction="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetCountryLis" +
            "tResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ATSUtilityService.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetCountryLis" +
            "tATSFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        ATSData.ATSUtilityService.RegionInfo[] GetCountryList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetPreCheckOu" +
            "tReportRatio", ReplyAction="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetPreCheckOu" +
            "tReportRatioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ATSUtilityService.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetPreCheckOu" +
            "tReportRatioATSFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        ATSData.ATSUtilityService.PreCheckOutReportRatio[] GetPreCheckOutReportRatio(ATSData.ATSUtilityService.PreCheckOutReportRequest objPreCheckOutReportRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetSalesProdu" +
            "cts", ReplyAction="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetSalesProdu" +
            "ctsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ATSUtilityService.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetSalesProdu" +
            "ctsATSFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        ATSData.ATSUtilityService.ProductInventory[] GetSalesProducts(int countryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetProductSal" +
            "esHistory", ReplyAction="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetProductSal" +
            "esHistoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ATSUtilityService.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetProductSal" +
            "esHistoryATSFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        ATSData.ATSUtilityService.ProductSalesHistory[] GetProductSalesHistory(int countryId, string productIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetInTransitH" +
            "istory", ReplyAction="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetInTransitH" +
            "istoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ATSUtilityService.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetInTransitH" +
            "istoryATSFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        ATSData.ATSUtilityService.InTransitHistoryResults[] GetInTransitHistory(int countryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/PremierRefere" +
            "nceSegments", ReplyAction="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/PremierRefere" +
            "nceSegmentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ATSUtilityService.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/PremierRefere" +
            "nceSegmentsATSFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        string PremierReferenceSegments(string Segment, ATSData.ATSUtilityService.SalesChannelOptions InSalesChannel, ATSData.ATSUtilityService.SalesChannelOptions OutSalesChannel, ATSData.ATSUtilityService.ActionMode ActionModes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/PutIntransitI" +
            "nfo", ReplyAction="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/PutIntransitI" +
            "nfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ATSUtilityService.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/PutIntransitI" +
            "nfoATSFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        ATSData.ATSUtilityService.IntransitResponse PutIntransitInfo(ATSData.ATSUtilityService.IntransitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GOPProcessOnH" +
            "and", ReplyAction="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GOPProcessOnH" +
            "andResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ATSUtilityService.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GOPProcessOnH" +
            "andATSFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        ATSData.ATSUtilityService.GOPTestHarnessOnHandResponse GOPProcessOnHand(ATSData.ATSUtilityService.GOPTestHarnessOnHandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/PutReliefOrde" +
            "rInfo", ReplyAction="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/PutReliefOrde" +
            "rInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ATSUtilityService.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/PutReliefOrde" +
            "rInfoATSFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        ATSData.ATSUtilityService.ReliefOrderResponse PutReliefOrderInfo(ATSData.ATSUtilityService.ReliefOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetTransactio" +
            "nDetails", ReplyAction="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetTransactio" +
            "nDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ATSUtilityService.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetTransactio" +
            "nDetailsATSFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        ATSData.ATSUtilityService.TransactionDetailResponse[] GetTransactionDetails(int regionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetDBJobDetai" +
            "ls", ReplyAction="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetDBJobDetai" +
            "lsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ATSUtilityService.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/GetDBJobDetai" +
            "lsATSFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        ATSData.ATSUtilityService.DbJobDetailsResponse[] GetDBJobDetails(int regionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/RunTheDBJob", ReplyAction="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/RunTheDBJobRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATSData.ATSUtilityService.ATSFaultDataContract), Action="http://schemas.dell.com/AvailableToSell/Utilities/ATSUtilityService/RunTheDBJobAT" +
            "SFaultDataContractFault", Name="ATSFaultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dell.AvailableToSell.Services.FaultContra" +
            "ct")]
        bool RunTheDBJob(string jobName, string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ATSUtilityServiceChannel : ATSData.ATSUtilityService.ATSUtilityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ATSUtilityServiceClient : System.ServiceModel.ClientBase<ATSData.ATSUtilityService.ATSUtilityService>, ATSData.ATSUtilityService.ATSUtilityService {
        
        public ATSUtilityServiceClient() {
        }
        
        public ATSUtilityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ATSUtilityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATSUtilityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATSUtilityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ATSData.ATSUtilityService.ProductEventLogInfo[] GetProductEventLogInformation(ATSData.ATSUtilityService.SearchProduct request) {
            return base.Channel.GetProductEventLogInformation(request);
        }
        
        public ATSData.ATSUtilityService.ProductDetails GetProductDetails(ATSData.ATSUtilityService.SearchProduct request) {
            return base.Channel.GetProductDetails(request);
        }
        
        public ATSData.ATSUtilityService.RegionInfo[] GetRegionList() {
            return base.Channel.GetRegionList();
        }
        
        public ATSData.ATSUtilityService.RegionInfo[] GetCountryList() {
            return base.Channel.GetCountryList();
        }
        
        public ATSData.ATSUtilityService.PreCheckOutReportRatio[] GetPreCheckOutReportRatio(ATSData.ATSUtilityService.PreCheckOutReportRequest objPreCheckOutReportRequest) {
            return base.Channel.GetPreCheckOutReportRatio(objPreCheckOutReportRequest);
        }
        
        public ATSData.ATSUtilityService.ProductInventory[] GetSalesProducts(int countryId) {
            return base.Channel.GetSalesProducts(countryId);
        }
        
        public ATSData.ATSUtilityService.ProductSalesHistory[] GetProductSalesHistory(int countryId, string productIDs) {
            return base.Channel.GetProductSalesHistory(countryId, productIDs);
        }
        
        public ATSData.ATSUtilityService.InTransitHistoryResults[] GetInTransitHistory(int countryId) {
            return base.Channel.GetInTransitHistory(countryId);
        }
        
        public string PremierReferenceSegments(string Segment, ATSData.ATSUtilityService.SalesChannelOptions InSalesChannel, ATSData.ATSUtilityService.SalesChannelOptions OutSalesChannel, ATSData.ATSUtilityService.ActionMode ActionModes) {
            return base.Channel.PremierReferenceSegments(Segment, InSalesChannel, OutSalesChannel, ActionModes);
        }
        
        public ATSData.ATSUtilityService.IntransitResponse PutIntransitInfo(ATSData.ATSUtilityService.IntransitRequest request) {
            return base.Channel.PutIntransitInfo(request);
        }
        
        public ATSData.ATSUtilityService.GOPTestHarnessOnHandResponse GOPProcessOnHand(ATSData.ATSUtilityService.GOPTestHarnessOnHandRequest request) {
            return base.Channel.GOPProcessOnHand(request);
        }
        
        public ATSData.ATSUtilityService.ReliefOrderResponse PutReliefOrderInfo(ATSData.ATSUtilityService.ReliefOrderRequest request) {
            return base.Channel.PutReliefOrderInfo(request);
        }
        
        public ATSData.ATSUtilityService.TransactionDetailResponse[] GetTransactionDetails(int regionId) {
            return base.Channel.GetTransactionDetails(regionId);
        }
        
        public ATSData.ATSUtilityService.DbJobDetailsResponse[] GetDBJobDetails(int regionId) {
            return base.Channel.GetDBJobDetails(regionId);
        }
        
        public bool RunTheDBJob(string jobName, string username) {
            return base.Channel.RunTheDBJob(jobName, username);
        }
    }
}
